let numero1;
let numero2;
let numero3;
numero1 = 5;
numero2 = 7;
numero3 = 9;
console.log("El promedio entre", numero1,",", numero2, "y", numero3, "es", (numero1 + numero2 + numero3) / 3);
numero1 = -2;
numero2 = -3;
numero3 = -8;
console.log("El promedio entre", numero1,",", numero2, "y", numero3, "es", (numero1 + numero2 + numero3) / 3);
numero1 = -1.2;
numero2 = 5.3;
numero3 = -3.3;
console.log("El promedio entre", numero1,",", numero2, "y", numero3, "es", (numero1 + numero2 + numero3) / 3);